version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
environment:
  build_user: JeremyTCD
  build_user_email: jeremytanchongdao@gmail.com
  nuget_key:
    secure: FOSfqqdiN4fPSFkcnR0mv5js+cq/MF+UGsoZV9FeKlJz3I7TDBQ0NxQSoAVcL2Pt
  git_key:
    secure: PxyfPAKDmw/E1ZbhsvQn53bu62I2wNJcegHokyaORVtq3CZuTpWGoOTpNn0U3JJY
install:
- ps: |
    Import-Module './src/GitUtils/GitUtils.psd1'
build: off
deploy_script:
- ps: |
    git config --global credential.helper store
    Add-Content "$($env:USERPROFILE)\.git-credentials" "https://$($env:git_key):x-oauth-basic@github.com`n"
    git config --global user.email $env:build_user_email
    git config --global user.name $env:build_user
    git checkout master -q
    Set-ChangelogFromTags
    git diff --quiet

    if($lastexitcode -eq 1){
        git add .
        git commit -m 'Update changelog' -q
        git push origin master -q
    }

    if($lastexitcode -eq 0){
        $moduleExists = Find-Module -Name GitUtils -RequiredVersion $env:APPVEYOR_REPO_TAG_NAME
        if(!$moduleExists){
            Update-ModuleManifest -Path './src/GitUtils/GitUtils.psd1' -ModuleVersion ${env:APPVEYOR_REPO_TAG_NAME}
            Publish-Module -Path './src/GitUtils' -NuGetApiKey ${env:nuget_key}
        }
    }
