version: '{build}'
image: Visual Studio 2017
environment:
  build_user: JeremyTCD
  build_user_email: jeremytanchongdao@gmail.com
  nuget_key:
    secure: FOSfqqdiN4fPSFkcnR0mv5js+cq/MF+UGsoZV9FeKlJz3I7TDBQ0NxQSoAVcL2Pt
  git_key:
    secure: PxyfPAKDmw/E1ZbhsvQn53bu62I2wNJcegHokyaORVtq3CZuTpWGoOTpNn0U3JJY
install:
- ps: Import-Module '.\src\GitUtils\GitUtils.psd1'
build: off
test_script: 
- ps: . '.\tools\AppVeyorTest.ps1'
deploy_script:
- ps: . '.\tools\AppVeyorDeploy.ps1'
